// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::speedtest_result_type::SpeedtestResult;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RecordSpeedtestArgs {
    pub speedtest: SpeedtestResult,
}

impl From<RecordSpeedtestArgs> for super::Reducer {
    fn from(args: RecordSpeedtestArgs) -> Self {
        Self::RecordSpeedtest {
            speedtest: args.speedtest,
        }
    }
}

impl __sdk::InModule for RecordSpeedtestArgs {
    type Module = super::RemoteModule;
}

pub struct RecordSpeedtestCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `record_speedtest`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait record_speedtest {
    /// Request that the remote module invoke the reducer `record_speedtest` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_record_speedtest`] callbacks.
    fn record_speedtest(&self, speedtest: SpeedtestResult) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `record_speedtest`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RecordSpeedtestCallbackId`] can be passed to [`Self::remove_on_record_speedtest`]
    /// to cancel the callback.
    fn on_record_speedtest(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &SpeedtestResult) + Send + 'static,
    ) -> RecordSpeedtestCallbackId;
    /// Cancel a callback previously registered by [`Self::on_record_speedtest`],
    /// causing it not to run in the future.
    fn remove_on_record_speedtest(&self, callback: RecordSpeedtestCallbackId);
}

impl record_speedtest for super::RemoteReducers {
    fn record_speedtest(&self, speedtest: SpeedtestResult) -> __sdk::Result<()> {
        self.imp
            .call_reducer("record_speedtest", RecordSpeedtestArgs { speedtest })
    }
    fn on_record_speedtest(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &SpeedtestResult) + Send + 'static,
    ) -> RecordSpeedtestCallbackId {
        RecordSpeedtestCallbackId(self.imp.on_reducer(
            "record_speedtest",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RecordSpeedtest { speedtest },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, speedtest)
            }),
        ))
    }
    fn remove_on_record_speedtest(&self, callback: RecordSpeedtestCallbackId) {
        self.imp.remove_on_reducer("record_speedtest", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `record_speedtest`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_record_speedtest {
    /// Set the call-reducer flags for the reducer `record_speedtest` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn record_speedtest(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_record_speedtest for super::SetReducerFlags {
    fn record_speedtest(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("record_speedtest", flags);
    }
}
