// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Server {
    pub id: u64,
    pub host: String,
    pub port: u16,
    pub name: String,
    pub location: String,
    pub country: String,
    pub ip: String,
}

impl __sdk::InModule for Server {
    type Module = super::RemoteModule;
}
