// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::bandwidth_type::Bandwidth;
use super::interface_type::Interface;
use super::ping_type::Ping;
use super::server_type::Server;
use super::speedtest_result_type::SpeedtestResult;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `speedtest`.
///
/// Obtain a handle from the [`SpeedtestTableAccess::speedtest`] method on [`super::RemoteTables`],
/// like `ctx.db.speedtest()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.speedtest().on_insert(...)`.
pub struct SpeedtestTableHandle<'ctx> {
    imp: __sdk::TableHandle<SpeedtestResult>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `speedtest`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SpeedtestTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SpeedtestTableHandle`], which mediates access to the table `speedtest`.
    fn speedtest(&self) -> SpeedtestTableHandle<'_>;
}

impl SpeedtestTableAccess for super::RemoteTables {
    fn speedtest(&self) -> SpeedtestTableHandle<'_> {
        SpeedtestTableHandle {
            imp: self.imp.get_table::<SpeedtestResult>("speedtest"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SpeedtestInsertCallbackId(__sdk::CallbackId);
pub struct SpeedtestDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SpeedtestTableHandle<'ctx> {
    type Row = SpeedtestResult;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SpeedtestResult> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SpeedtestInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpeedtestInsertCallbackId {
        SpeedtestInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SpeedtestInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SpeedtestDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpeedtestDeleteCallbackId {
        SpeedtestDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SpeedtestDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SpeedtestResult>("speedtest");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}
pub struct SpeedtestUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SpeedtestTableHandle<'ctx> {
    type UpdateCallbackId = SpeedtestUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SpeedtestUpdateCallbackId {
        SpeedtestUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SpeedtestUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SpeedtestResult>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SpeedtestResult>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `speedtest`,
/// which allows point queries on the field of the same name
/// via the [`SpeedtestIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.speedtest().id().find(...)`.
pub struct SpeedtestIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SpeedtestResult, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SpeedtestTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `speedtest`.
    pub fn id(&self) -> SpeedtestIdUnique<'ctx> {
        SpeedtestIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SpeedtestIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<SpeedtestResult> {
        self.imp.find(col_val)
    }
}
